# Day 46: Create a DataFrame
Create a Dataframe using pandas. You are going to create a code to put the following into a Dataframe. You will use the
information in the table below. Basically, you are going to recreate this table using pandas. Use the information in the table to recreate the table.
year Title genre
2009 Brothers Drama
2002 Spider-Man Sci-fi
2009 WatchMen Drama
2010 Inception Sci-fi
2009 Avatar Fantasy

In [21]:
import pandas as pd

In [22]:
a = [2009, 'Brothers', 'Drama']
b = [2002, 'Spider-Man', 'Sci-fi']
c = [2009, 'WatchMen', 'Drama']
d = [2010, 'Inception', 'Sci-fi']
e = [2009, 'Avatar', 'Fantasy']

In [23]:
df = pd.DataFrame(zip(a,b,c,d,e), index= ['year', 'Title', 'genre']).T
df

   year       Title    genre
0  2009    Brothers    Drama
1  2002  Spider-Man   Sci-fi
2  2009    WatchMen    Drama
3  2010   Inception   Sci-fi
4  2009      Avatar  Fantasy

# Extra Challenge: Website Data with Pandas
Create a code that extracts data from a website. You will extract a
table from the website. And from that table you will extract columns
about the data types in Python and their mutability. You will extract
information from the following website:
https://en.wikipedia.org/wiki/Python_(programming_language)
The following table (next page) is what you will extract from the
website.
Once you extract this table, you will write a code that will extract
the data types and their mutability (Two columns). Here is how
your output should look:

In [25]:
url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'

In [76]:
web = pd.read_html(url)
table = web[1]
table

,Type,Mutability,Description,Syntax examples
0,bool,immutable,Boolean value,TrueFalse
1,bytearray,mutable,Sequence of bytes,"bytearray(b'Some ASCII')bytearray(b""Some ASCII..."
2,bytes,immutable,Sequence of bytes,"b'Some ASCII'b""Some ASCII""bytes([119, 105, 107..."
3,complex,immutable,Complex number with real and imaginary parts,3+2.7j3 + 2.7j
4,dict,mutable,Associative array (or dictionary) of key and v...,"{'key1': 1.0, 3: False}{}"
5,types.EllipsisType,immutable,An ellipsis placeholder to be used as an index...,...Ellipsis
6,float,immutable,Double-precision floating-point number. The pr...,1.33333
7,frozenset,immutable,"Unordered set, contains no duplicates; can con...","frozenset([4.0, 'string', True])"
8,int,immutable,Integer of unlimited magnitude[107],42
9,list,mutable,"List, can contain mixed types","[4.0, 'string', True][]"
10,types.NoneType,immutable,"An object representing the absence of a value,...",None
11,types.NotImplementedType,immutable,A placeholder that can be returned from overlo...,NotImplemented
12,range,immutable,An immutable sequence of numbers commonly used...,"range(-1, 10)range(10, -5, -2)"
13,set,mutable,"Unordered set, contains no duplicates; can con...","{4.0, 'string', True}set()"
14,str,immutable,A character string: sequence of Unicode codepo...,"'Wikipedia'""Wikipedia""""""""Spanning multiple lin..."
15,tuple,immutable,Can contain mixed types,"(4.0, 'string', True)('single element',)()"

In [111]:
len(web)

13

In [ ]:
for index, val in enumerate(web):
    if "Mutability" in val:
        ind = index
print(ind)

In [88]:
df1 = pd.DataFrame(table, columns =['Type', 'Mutability'])
df1

                        Type Mutability
0                       bool  immutable
1                  bytearray    mutable
2                      bytes  immutable
3                    complex  immutable
4                       dict    mutable
5         types.EllipsisType  immutable
6                      float  immutable
7                  frozenset  immutable
8                        int  immutable
9                       list    mutable
10            types.NoneType  immutable
11  types.NotImplementedType  immutable
12                     range  immutable
13                       set    mutable
14                       str  immutable
15                     tuple  immutable

In [91]:
web.index("Summary of Python 3's built-in types")

,vteNumerical-analysis software,vteNumerical-analysis software.1
0,Free,Advanced Simulation Library ADMB Chapel Euler ...
1,Proprietary,DADiSP FEATool Multiphysics GAUSS LabVIEW Mapl...
2,Comparison,Comparison

In [110]:
for index, val in enumerate(web):
    if "Mutability" in val:
        ind = index
print(ind)

1